name: e2e
# Runs the CI end-to-end test network on all pushes to master or release branches
# and every pull request, but only if any Go files have been changed.
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

env:
  TAG: ostracon/e2e-node:local-version # See test/e2e/Makefile:docker
  CACHE_DIR: /tmp/ostracon/e2etest

jobs:
  e2e-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      CACHE_FILE: ${{ steps.prep.outputs.CACHE_FILE }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum

      - name: Create cache directory
        run: |
          mkdir -p /tmp/.buildx-cache
          mkdir -p ${{ env.CACHE_DIR }}

      - name: Prepare
        id: prep
        run: |
          HASH_GHE=${{ github.sha }}
          VARIANT=$(TZ=UTC-9 date '+%Y%m')${HASH_GHE:0:7}
          NAME_TAR="${VARIANT}.tar"
          CACHE_FILE=${{ env.CACHE_DIR }}"/${NAME_TAR}"
          echo "CACHE_FILE=${CACHE_FILE}" >> $GITHUB_OUTPUT
        if: "env.GIT_DIFF != ''"

      - name: Get Docker Image File from cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ steps.prep.outputs.CACHE_FILE }}
        if: "env.GIT_DIFF != ''"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: "env.GIT_DIFF != '' && steps.cache.outputs.cache-hit != 'true'"

      - name: Get cached Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        if: "env.GIT_DIFF != '' && steps.cache.outputs.cache-hit != 'true'"

      - name: Build e2e Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./test/e2e/docker/Dockerfile
          tags: ${{ env.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          load: true
        if: "env.GIT_DIFF != '' && steps.cache.outputs.cache-hit != 'true'"

      - name: Move cached Docker layers
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        if: "env.GIT_DIFF != '' && steps.cache.outputs.cache-hit != 'true'"

      - name: Save Docker Image
        run: |
          docker save -o ${{ steps.prep.outputs.CACHE_FILE }} ${{ env.TAG }}
        if: "env.GIT_DIFF != '' && steps.cache.outputs.cache-hit != 'true'"

  e2e-test:
    needs: e2e-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum

      - name: Get Docker Image File from cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ needs.e2e-build.outputs.CACHE_FILE }}
        if: "env.GIT_DIFF != ''"

      - name: Load Docker Image on Docker
        run: |
          docker load -i ${{ needs.e2e-build.outputs.CACHE_FILE }}
        if: "env.GIT_DIFF != ''"

      - name: Build e2e runner
        working-directory: test/e2e
        run: make runner
        if: "env.GIT_DIFF != ''"

      - name: Run CI testnet
        working-directory: test/e2e
        run: ./build/runner -f networks/ci.toml
        if: "env.GIT_DIFF != ''"

      - name: Emit logs on failure
        if: ${{ failure() }}
        working-directory: test/e2e
        run: ./build/runner -f networks/ci.toml logs
